language: node_js
jobs:
  include:
    - stage: test
      script: npm run build

    - stage: build and deploy
      env: BUCKET=integration-kvt.kinesisgroup.io TRAVIS_TAG=true
      if: branch = master and type = push
      script: npm run build
      deploy: &deploy
        provider: s3
        region: ap-southeast-2
        skip_cleanup: true
        bucket: $BUCKET
        on:
          tags: true
    - stage: build and deploy
      env: BUCKET=uat-kvt.kinesisgroup.io
      if: tag is present
      script: npm run build
      deploy:
        <<: *deploy
    - env: BUCKET=kvt.kinesisgroup.io
      if: tag is present and tag =~ ^((?!beta).)*$
      script: npm run build
      deploy:
        <<: *deploy
