import * as React from 'react'
// import { Link as ScrolLink } from 'react-scroll'

export const BuyingToken: React.SFC = (props) => (
  <div>
    <div className='section_title text-center mb-60'>
      <h2>The Kinesis Velocity Token Crowdsale Process</h2>
    </div>
    <div>
      <h3>Buying KVT</h3>
      <p>Register your interest HERE.</p>
      <p>Be ready with your Ethereum payment to receive your Kinesis Velocity Tokens directly into your ERC20 token compatible eWallet.</p>
      <p>At the nominated date and time, buy your Kinesis Tokens (KVT) y following the user-friendly instructions on our website.</p>
    </div>
    <div>
      <h3>KVT Distribution</h3>
      <p>Kinesis Velocity Tokens will be distributed to the eWallet address used to make your purchase. They will be displayed as “distributed/provisional” until full KYC has been performed [LC3]</p>
      <p>Upon completion of KYC and assessment against the crowd-sale targets , your KVT’s will be activated.</p>
      <p>Once you have received your activated KVRT’s you will be eligible to receive 20% of all transaction fees generated by all Kinesis crypto currencies in circulation. BSo by participating investing in this time-limited token sale, a holder of a KVT  will gain superior ongoing returns based simply on the Kinesis crypto currency which will launch on completion of successful KVRT issue.</p>
    </div>
    <div>
      <h3>Six Kinesis Velocity Token Fast Facts</h3>
      <ol style={{listStyleType: 'decimal', paddingLeft: '20px'}}>
        <li><p>Participants are required to purchase a minimum of XXX Kinesis Velocity Tokens.</p></li>
        <li><p>Each Kinesis Velocity Token empowers the holder to share in a 20% share of all transaction fees associated with each Kinesis Currency.</p></li>
        <li><p>Pre-Sale firm commitments are entitled to a 25% discount. This is a limited opportunity and ends on 1st March 2018.</p></li>
        <li><p>All unsold Kinesis Velocity Tokens will be destroyed, which in the unlikely event that there are unsold Tokens remaining, your stake may increase, further bolstering the earning potential of the Kinesis Velocity Token.</p></li>
        <li><p>You may purchase the Kinesis Velocity Token with Ethereum, or Fiat currency.</p></li>
        <li><p>Tokens may become tradeable on secondary marketplaces and pricing will depend on general market forces</p></li>
      </ol>
    </div>
    <div>
      <table>
        <tr>
          <th>Token Name</th>
          <th>Kinesis Velocity Token</th>
        </tr>
        <tr>
          <th>Token Symbol</th>
          <td>KVT</td>
        </tr>
        <tr>
          <th>Pre-Sale Timing</th>
          <td>12 February 2018</td>
        </tr>
        <tr>
          <th>Public Sale Timing</th>
          <td>1 March 2018</td>
        </tr>
        <tr>
          <th>Pre-Sale Discount</th>
          <td>25%</td>
        </tr>
        <tr>
          <th>Issue price of Tokens</th>
          <td>USD$1000</td>
        </tr>
        <tr>
          <th>Sale Size Limits</th>
          <td>Technically and legally hard capped at 300,000 KVTs. Post 250,000 subscribed a maximum of 5 KVTs available per subscriber for this offer. KVTs not sold will be held for a subsequent issue no sooner than 1 May 2019 at the prvailing market price.</td>
        </tr>
        <tr>
          <th>Further Token Issuance</th>
          <td>No, there will never be any dilution to the rights of KVT holders</td>
        </tr>
        <tr>
          <th>Secured methods of token purchase</th>
          <td>Fiat & Ehtereum (ETH)</td>
        </tr>
        <tr>
          <th>Token holder rights & benefits</th>
          <td>20% of all transaction fees of Kinesis cryptocurrency suite. The exclusive right to participate in the Kinesis currency ICO with pre-ICO preferential rates.</td>
        </tr>
        <tr>
          <th>Token Issuance date</th>
          <td>Immediately as subscribed</td>
        </tr>
        <tr>
          <th>Token Activation date</th>
          <td>Latest 1 May 2018</td>
        </tr>
        <tr>
          <th>Token Buy-Back Program</th>
          <td>A minimum of 5% of total transaction fees goes towards buying back token. Buy-back of tokens increased to 20% of transaction fees if token price goes 5% below listing price</td>
        </tr>
      </table>
    </div>
  </div>
)
