import * as React from 'react'

export const Home: React.SFC = () => {
  return (
    <div>
      <section className='banner pt-80 style_2' data-stellar-background-ratio='.7' id='home'>
        <div className='overlay' />
        <div className='container'>
          <h1 className='mb-10 light_color' style={{ textAlign: 'center' }}><span className='primary_color'>Kinesis</span></h1>
          <ul style={{listStyleType: 'disc'}}>
            <li style={{fontSize: '16px', marginBottom: '12px'}}>Kinesis is a revolutionary digital currency backed by physical bullion, supercharged by transactional velocity, and for the first time in history; achieving a yield over physical precious metals.</li>
            <li style={{fontSize: '16px', marginBottom: '12px'}}>Maximize your potential yield with the Kinesis Revenue Token: Claim your stake in the massive earning potential of the digital currency of the future. Each Kinesis Revenue Token guarantees the buyer to share in all transaction fees generated by the Kinesis digital currencies.</li>
            <li style={{fontSize: '16px', marginBottom: '12px'}}>Kinesis is a currency built for high frequency transactions, use in the real world, and backed by physical precious metals. Kinesis is empowering users to receive a desirable yield on gold and silver.</li>
          </ul>
          { /* <a href='#' style={{ paddingLeft: '12px', paddingRight: '12px' }} className='ml-5 mr-5 mb-20 btn prehighlight '>Open Trading Account</a>
          <a href='#' style={{ paddingLeft: '12px', paddingRight: '12px' }} className='ml-5 mr-5 mb-20 btn'>Open Demo Account</a> */ }
        </div>
      </section>
    </div>
  )
}
