import * as React from 'react'
import { DisplayMore } from '../DisplayMore';
import { BuyingToken } from './BuyingToken'
import { MoreKvtInfo } from './MoreKvtInfo'
const Scroll: any = require('react-scroll')
const ScrollLink = Scroll.Link

export class TokenOffering extends React.Component<null, null> {
  constructor(props: any) {
    super(props)
  }

  public render() {

    return (
      <div>
        <section className='services pt-80 pb-80' style={{color: 'white'}} id='token'>
          <div className='container'>
            <div className='section_title text-center'>
              <h2>Kinesis Velocity Token Offering</h2>

              <p><strong>The Kinesis Velocity Token (KVT) Initial Token Offer (ITO) offers an investor a one time only opportunity to: </strong></p>

              <p>
                <ul style={{listStyleType: 'circle', marginLeft: '40px'}}>
                  <li>Receive discounted rates on subscribed KVTs;</li>
                  <li>Access a share in 20% of all aggregated transaction fees generated by the Kinesis currency suite;</li>
                  <li>Access a 20% share of commissions generated in the Kinesis Commercial Center;</li>
                  <li>Benefit from anticipated significant capital gains on the KVTs themselves; </li>
                  <li>Access the extraordinary pre-ICO benefits on offer for the Kinesis digital currency suite. </li>
                </ul>
              </p>

              <p>KVTs are in limited supply, with phased discounted rates applying. The earlier one invests the greater the discount.</p>
              <p>Stake your claim to the economic benefits of the monetary system of the future.</p>
              <ScrollLink style={{ paddingLeft: '12px', paddingRight: '12px', marginBottom: '40px'}} className='ml-5 mr-5 mb-20 btn prehighlight' to='contact' spy={true} smooth={true} offset={0} duration={500}>Register Your Interest</ScrollLink>

              <div className='container faq' style={{backgroundColor: 'rgba(0,0,0,0)', marginTop: '10px', maxWidth: '1000px' }}>
                <div className='row'>
                  <div style={{width: '100%', marginLeft: '5px'}}>
                    <div>
                      <div className='panel-group' id='accordionKvtInfo' role='tablist' aria-multiselectable='true'>
                        <div className='panel panel-default'>
                          <div className='panel-heading' role='tab' id='headingMoreKvtInfo'>
                            <h4 className='panel-title'>
                              <a role='button' className='collapsed' data-toggle='collapse' data-parent='#accordionKvtInfo' href='#collapseMoreKvtInfo' aria-expanded='false' aria-controls='collapseMoreKvtInfo'>
                                More KVT Details<i className='fa fa-caret-up' />
                              </a>
                            </h4>
                          </div>
                          {/* End of .panel-heading */}
                          <div id='collapseMoreKvtInfo' className='panel-collapse collapse' role='tabpanel' aria-labelledby='headingMoreKvtInfo'>
                            <div className='panel-body'>
                              <MoreKvtInfo />
                            </div>
                            {/* End of .panel-body */}
                          </div>
                          {/* End of .panel-collapse */}
                        </div>
                        {/* End of .panel */}
                      </div>
                      <div className='panel-group' id='accordionBuyKvt' role='tablist' aria-multiselectable='true'>
                        <div className='panel panel-default'>
                          <div className='panel-heading' role='tab' id='headingBuyKvt'>
                            <h4 className='panel-title'>
                              <a role='button' className='collapsed' data-toggle='collapse' data-parent='#accordionBuyKvt' href='#collapseBuyKvt' aria-expanded='false' aria-controls='collapseBuyKvt'>
                                How To Buy KVT?<i className='fa fa-caret-up' />
                              </a>
                            </h4>
                          </div>
                          {/* End of .panel-heading */}
                          <div id='collapseBuyKvt' className='panel-collapse collapse' role='tabpanel' aria-labelledby='headingBuyKvt'>
                            <div className='panel-body'>
                              <BuyingToken />
                            </div>
                            {/* End of .panel-body */}
                          </div>
                          {/* End of .panel-collapse */}
                        </div>
                        {/* End of .panel */}
                      </div>
                      {/* End of .panel-group */}
                    </div>
                    {/* End of .content */}
                  </div>
                  {/* End of .col-sm-8 */}
                </div>
                {/* End of .row */}
              </div>
            </div>
          </div>
        </section>
      </div>
    )
  }
}
